import test from 'node:test';import assert from 'node:assert/strict';
import * as E from '../src/engine.js';import {ai,infer} from '../src/ai.js';import {RoomService} from '../src/rooms.js';
const players=n=>Array.from({length:n},(_,i)=>({name:'Tester '+i,type:'human'}));
const card=id=>E.deck().find(c=>c.id===id);
function fixture(round=1,rules=E.classic){let g=E.create(players(3),rules,7);Object.assign(g,{hands:[[card('S14'),card('S2')],[card('H14'),card('H2')],[card('S3'),card('S4')]],currentPlayer:0,round,opening:round===1});return g;}
function invariant(g){const cards=[...g.hands.flat(),...g.trick.map(x=>x.card),...g.discarded];assert.equal(cards.length,52);assert.equal(new Set(cards.map(c=>c.id)).size,52);for(let p=0;p<g.players.length;p++){assert(g.known[p].every(c=>g.hands[p].some(h=>h.id===c.id)));assert(g.voids[p].every(s=>!g.hands[p].some(c=>c.suit===s)));}}
test('Ace holder may open any card; server engine enforces turns and suits',()=>{const g=E.create(players(4),E.classic,20);assert.equal(E.legal(g).length,g.hands[g.currentPlayer].length);const c=E.legal(g).find(c=>c.id!=='S14');const h=E.play(g,g.currentPlayer,c.id);assert.equal(h.leadSuit,c.suit);assert.throws(()=>E.play(g,(g.currentPlayer+1)%4,c.id));assert.throws(()=>E.play(g,g.currentPlayer,'fake'));});
test('No first-round Vettu, trump or collection; round two cuts normally',()=>{for(const rules of [E.classic,E.trump]){let g=fixture(1,rules);g=E.play(g,0,'S2');g=E.play(g,1,'H2');assert.equal(g.result,null);assert.equal(g.trick[1].cut,false);assert.equal(g.trumpSuit,null);g=E.play(g,2,'S3');assert.equal(g.result.collector,null);let h=fixture(2,rules);h=E.play(h,0,'S2');h=E.play(h,1,'H2');assert.equal(h.trick[1].cut,true);if(rules.cutEnds)assert.equal(h.result.collector,0);else assert.equal(h.trumpSuit,'H');}});
test('Names required and views never expose private hands or shuffle seed',()=>{assert.throws(()=>E.create([{name:' ',type:'human'},players(1)[0]]));let g=E.create(players(4),E.classic,9);const v=E.view(g,0);assert(!('hands'in v));assert(!('seed'in v));assert.throws(()=>ai(g,'Hard'));assert.deepEqual(infer(v)[0].known,v.hand);});
test('All difficulties play legal moves to completion; cards and inference conserved',()=>{for(const rules of [E.classic,E.trump])for(const difficulty of ['Easy','Medium','Hard']){let g=E.create(players(4),rules,57);let moves=0;while(g.status==='playing'&&moves++<1800){invariant(g);if(g.result)g=E.resolve(g);else{const v=E.view(g,g.currentPlayer),c=ai(v,difficulty,moves).card;assert(E.legal(v).some(x=>x.id===c.id));g=E.play(g,g.currentPlayer,c.id);}}invariant(g);assert.notEqual(g.status,'playing',difficulty+' did not finish');}});
test('Room create/join/start/play idempotency, reconnect, host transfer and intentional exit',()=>{let time=1000;const s=new RoomService(()=>time);const create={op:'create',name:'Host',count:3,requestId:'create-123'};const h=s.request(create);assert.equal(s.request(create).token,h.token);const join={op:'join',code:h.code,name:'Guest',requestId:'join-1234'};const g=s.request(join);assert.equal(s.request(join).token,g.token);assert.equal(s.rooms.get(h.code).members.length,2);assert.equal(s.request({...join,token:g.token}).seat,g.seat);const start={...h,op:'start',requestId:'start-123'};const st=s.request(start);assert.equal(s.request(start).game.id,st.game.id);const room=s.rooms.get(h.code);const seat=room.game.currentPlayer;if(seat<2){const member=seat===0?h:g;const move={...member,op:'play',card:E.legal(room.game)[0].id,expectedGameId:st.game.id,expectedMoves:0,requestId:'play-12345'};s.request(move);s.request(move);assert.equal(room.game.moves,1);assert.throws(()=>s.request({...move,requestId:'play-56789'}));}s.request({...h,op:'leave',requestId:'leave-123'});assert.equal(room.hostSeat,g.seat);assert.equal(room.seats[0].type,'ai');assert.throws(()=>s.request({...h,op:'poll'}));assert.equal(s.request({...g,op:'poll'}).seat,1);const serialized=s.serialize();const restored=new RoomService(()=>time);restored.restore(serialized);assert.equal(restored.request({...g,op:'poll'}).game.id,room.game.id);});
test('A Vettu pickup removes stale void inference',()=>{let g=fixture(2);g.hands[0]=[card('S2')];g.voids[0]=['H'];g=E.play(g,0,'S2');g=E.play(g,1,'H2');g=E.resolve(g);assert(!g.voids[0].includes('H'));assert(g.known[0].some(c=>c.id==='H2'));});
