const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('fs');const assert=require('assert/strict');const wait=ms=>new Promise(r=>setTimeout(r,ms));
const errors=[];
function fakeAudio(){let gain={value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}};let node=()=>({gain:{...gain},frequency:{...gain},connect(n){return n},disconnect(){},start(){},stop(){}});return class {constructor(){this.sampleRate=8000;this.currentTime=0;this.destination=node()}resume(){}close(){}createBuffer(c,l){return {getChannelData:()=>new Float32Array(l)}}createBufferSource(){return node()}createBiquadFilter(){return node()}createGain(){return node()}createOscillator(){return node()}}}
function open(port,storage={}){let virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>{if(!/canvas|not implemented/i.test(e.message))errors.push(e.message)});
return new JSDOM(fs.readFileSync(require('path').join(__dirname,'../dist/index.html'),'utf8'),{url:'https://kazhutha-online.onrender.com/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse(w){for(const [key,value] of Object.entries(storage))w.localStorage.setItem(key,value);w.structuredClone=structuredClone;w.AbortController=AbortController;w.ResizeObserver=class{observe(){}disconnect(){}};w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.visualViewport={width:844,height:390,addEventListener(){}};w.AudioContext=fakeAudio();w.fetch=(url,options)=>{if(w.__offline)return Promise.reject(Error('Simulated offline'));assert.equal(url,'https://kazhutha-online.onrender.com/api/game');return fetch('http://127.0.0.1:'+port+'/api/game',options)};w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLElement.prototype.hasPointerCapture=()=>false;w.HTMLElement.prototype.setPointerCapture=()=>{};w.HTMLElement.prototype.releasePointerCapture=()=>{};}});}
function button(d,text){const b=[...d.window.document.querySelectorAll('button')].find(b=>b.textContent.trim()===text||b.textContent.trim().startsWith(text));assert(b,'Missing button '+text);assert(!b.disabled,'Disabled '+text);b.click();}
function input(d,label,value){const el=d.window.document.querySelector('input[aria-label="'+label+'"]');assert(el,'Missing input '+label);Object.getOwnPropertyDescriptor(d.window.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new d.window.Event('input',{bubbles:true}));el.dispatchEvent(new d.window.Event('change',{bubbles:true}));}
(async()=>{const {createApp}=await import('../server.mjs');const {server,service}=createApp();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;let h=open(port),g=open(port);try{
await wait(200);button(h,'Play with friends');await wait(100);assert.equal(h.window.document.querySelector('input[aria-label="Player 1 name"]').value,'');button(h,'Create private room');await wait(50);assert.equal(service.rooms.size,0);
input(h,'Player 1 name','Host Test');await wait(50);button(h,'Create private room');await wait(200);if(!service.rooms.size)console.log('DEBUG',h.window.document.querySelector('.error-toast')?.textContent,errors);assert.equal(service.rooms.size,1);const room=[...service.rooms.values()][0];
button(g,'Play with friends');await wait(100);input(g,'Player 1 name','Guest Test');input(g,'Room code',room.code);await wait(50);button(g,'Join / reconnect');await wait(200);assert.equal(room.members.length,2);button(h,'Start the game');await wait(1400);assert(room.game);assert(h.window.document.querySelector('.hand-zone'));assert(g.window.document.querySelector('.hand-zone'));
for(const d of [h,g])assert(!/ChatGPT|sign in/i.test(d.window.document.querySelector('main').textContent));
const storage={...h.window.localStorage};h.window.close();h=open(port,storage);await wait(1300);assert(h.window.document.querySelector('.hand-zone'));assert.equal(room.members.length,2);
g.window.__offline=true;g.window.dispatchEvent(new g.window.Event('offline'));await wait(100);assert(g.window.document.querySelector('.room-connection').textContent.includes('Reconnecting'));g.window.__offline=false;g.window.dispatchEvent(new g.window.Event('online'));await wait(200);assert.equal(room.members.length,2);

button(h,'Exit Game');await wait(100);assert(h.window.document.querySelector('[role="dialog"]').textContent.includes('Are you sure'));const exit=[...h.window.document.querySelectorAll('[role="dialog"] button')].find(b=>b.textContent==='Exit Game');exit.click();await wait(200);assert.equal(room.members.length,1);assert.equal(room.hostSeat,1);console.log('PASS isolated frontend clients: blank name, create, join, start, hands, exit confirmation, server leave, host transfer, reload resume, offline reconnect.');assert.deepEqual(errors,[]);console.log('PASS no unexpected frontend runtime errors');
}finally{h.window.close();g.window.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
